### ISSUE TITLE
ecc() with missing .f

### ISSUE THREAD

**Issue by wrathematics** [bearloga/MLPUGS#4]
The help says that if a `.f` is not supplied, then a built-in one will be used. Currently that doesn't happen, for example:

``` r
library(MLPUGS)
x <- movies_train[, -(1:3)]
y <- movies_train[, 1:3]
fit <- ecc(x, y, m = 1)
```

produces the error

```
Error in system.time({ : could not find function ".f"
```

The `.f` documentation block suggests checking the details section, but `ecc.R` doesn't have an `@details` block.

**Comment by bearloga** [comment]
Whoops. There was a point early on when I was using my own tree-based, in-dev package and I thought I had gotten all the references to it out but missed that one. Since I ended up using `glm()` in the examples to avoid dependencies, I'm now wondering if I should just make that the default base classifier since it's part of R core. Thoughts?

**Comment by wrathematics** [comment]
Well, I don't think it's unreasonable to just not have a default, particularly if you give lots of examples.  Adding more examples to the vignette, or having a separate vignette just showing some example syntax for a variety of classifiers would be nice.

If you're going to have a default, my personal bias for one would be something simple and fast, like naive Bayes or even knn. Although I don't think either of those is in R core. But if you're just restricting to the 2-class case, you could implement naive Bayes very easily. Of course, no default would be easiest of all ;)

Edit: when I say an example vignette, I don't really mean analyses. Just a "here's syntax for model x, and here's the syntax for model y" kind of thing.
